import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

/// Mapeo de nombres de iconos Ionicons (usados en el frontend original)
/// a IconData de Material Design, 1:1 pantallas y acciones.
const Map<String, IconData> _iconos = <String, IconData>{
  'home': Icons.home,
  'home-outline': Icons.home_outlined,
  'menu': Icons.menu,
  'menu-outline': Icons.menu,
  'close': Icons.close,
  'close-outline': Icons.close,
  'add': Icons.add,
  'add-circle': Icons.add_circle,
  'add-circle-outline': Icons.add_circle_outline,
  'trash': Icons.delete,
  'trash-outline': Icons.delete_outline,
  'trash-bin': Icons.delete_outline,
  'trash-bin-outline': Icons.delete_outline,
  'create': Icons.edit,
  'create-outline': Icons.edit_outlined,
  'pencil': Icons.edit_outlined,
  'search': Icons.search,
  'cart': Icons.shopping_cart,
  'cart-outline': Icons.shopping_cart_outlined,
  'cube': Icons.inventory_2,
  'cube-outline': Icons.inventory_2_outlined,
  'layers': Icons.layers,
  'layers-outline': Icons.layers_outlined,
  'swap-horizontal': Icons.swap_horiz,
  'swap-vertical': Icons.swap_vert,
  'sync': Icons.sync,
  'people': Icons.people,
  'people-outline': Icons.people_outline,
  'person': Icons.person,
  'person-outline': Icons.person_outlined,
  'person-circle': Icons.account_circle,
  'person-circle-outline': Icons.account_circle_outlined,
  'person-add': Icons.person_add,
  'person-add-outline': Icons.person_add_outlined,
  'chevron-forward': Icons.chevron_right,
  'chevron-back': Icons.chevron_left,
  'chevron-down': Icons.expand_more,
  'chevron-up': Icons.expand_less,
  'chevron-left': Icons.chevron_left,
  'chevron-right': Icons.chevron_right,
  'arrow-back': Icons.arrow_back,
  'arrow-forward': Icons.arrow_forward,
  'arrow-up': Icons.arrow_upward,
  'arrow-down': Icons.arrow_downward,
  'arrow-up-circle': Icons.arrow_circle_up,
  'arrow-up-circle-outline': Icons.arrow_circle_up_outlined,
  'arrow-down-circle': Icons.arrow_circle_down,
  'arrow-down-circle-outline': Icons.arrow_circle_down_outlined,
  'trending-up': Icons.trending_up,
  'trending-down': Icons.trending_down,
  'alert': Icons.error,
  'alert-outline': Icons.error_outline,
  'alert-circle': Icons.error,
  'alert-circle-outline': Icons.error_outline,
  'warning': Icons.warning_amber,
  'warning-outline': Icons.warning_amber_rounded,
  'checkmark': Icons.check,
  'checkmark-circle': Icons.check_circle,
  'checkmark-circle-outline': Icons.check_circle_outline,
  'checkmark-done': Icons.done_all,
  'checkmark-done-outline': Icons.done_all,
  'wallet': Icons.account_balance_wallet_outlined,
  'card': Icons.credit_card,
  'cash': Icons.payments_outlined,
  'cash-outline': Icons.payments_outlined,
  'receipt': Icons.receipt_long,
  'receipt-outline': Icons.receipt_long_outlined,
  'time': Icons.schedule,
  'time-outline': Icons.schedule_outlined,
  'today': Icons.today,
  'calendar': Icons.calendar_month,
  'calendar-outline': Icons.calendar_month_outlined,
  'lock-closed': Icons.lock,
  'lock-closed-outline': Icons.lock_outline,
  'lock-open': Icons.lock_open,
  'lock-open-outline': Icons.lock_open_outlined,
  'finger-print': Icons.fingerprint,
  'log-out': Icons.logout,
  'log-out-outline': Icons.logout,
  'power': Icons.power_settings_new,
  'settings': Icons.settings,
  'settings-outline': Icons.settings_outlined,
  'eye': Icons.visibility,
  'eye-outline': Icons.visibility_outlined,
  'eye-off': Icons.visibility_off,
  'eye-off-outline': Icons.visibility_off_outlined,
  'refresh': Icons.refresh,
  'refresh-circle': Icons.refresh,
  'camera': Icons.photo_camera,
  'camera-outline': Icons.photo_camera_outlined,
  'images': Icons.image,
  'image': Icons.image,
  'image-outline': Icons.image_outlined,
  'key': Icons.key,
  'key-outline': Icons.key_outlined,
  'shield-checkmark': Icons.shield,
  'shield-checkmark-outline': Icons.shield_outlined,
  'globe': Icons.public,
  'globe-outline': Icons.public,
  'mail': Icons.mail,
  'mail-outline': Icons.mail_outlined,
  'call': Icons.call,
  'call-outline': Icons.call_outlined,
  'phone-portrait': Icons.smartphone,
  'phone-portrait-outline': Icons.smartphone_outlined,
  'radio-button-on': Icons.radio_button_checked,
  'radio-button-off': Icons.radio_button_unchecked,
  'ellipse-outline': Icons.circle_outlined,
  'build': Icons.build,
  'build-outline': Icons.build_outlined,
  'hammer': Icons.hardware,
  'qr-code': Icons.qr_code,
  'qr-code-outline': Icons.qr_code,
  'barcode': Icons.pin_outlined,
  'storefront': Icons.storefront,
  'storefront-outline': Icons.storefront_outlined,
  'business': Icons.business,
  'business-outline': Icons.business_outlined,
  'notifications-off': Icons.notifications_off_outlined,
  'ban': Icons.block,
  'file-tray-outline': Icons.folder_outlined,
  'keypad': Icons.calendar_view_day,
  'backspace': Icons.backspace_outlined,
  'shirt': Icons.checkroom,
  'wine': Icons.local_bar,
  'beer': Icons.sports_bar,
  'flask': Icons.science,
  'cafe': Icons.local_cafe,
  'caret-up': Icons.keyboard_arrow_up,
  'caret-down': Icons.keyboard_arrow_down,
  'speedometer': Icons.speed,
  'speedometer-outline': Icons.speed_outlined,
  'contract': Icons.receipt_long,
  'contract-outline': Icons.receipt_long_outlined,
  'newspaper': Icons.newspaper,
  'newspaper-outline': Icons.newspaper_outlined,
  'ellipsis-horizontal': Icons.more_horiz,
  'ellipsis-vertical': Icons.more_vert,
  'ellipsis-vertical-outline': Icons.more_vert,
  'filter': Icons.filter_list,
  'funnel': Icons.filter_alt,
  'scan': Icons.document_scanner_outlined,
  'barbell': Icons.fitness_center,
  'hourglass': Icons.hourglass_empty,
  'hourglass-outline': Icons.hourglass_empty,
  'shield-outline': Icons.shield_outlined,
  'pricetag': Icons.local_offer,
  'pricetag-outline': Icons.local_offer_outlined,
  'grid': Icons.grid_view,
  'grid-outline': Icons.grid_view_outlined,
  'list': Icons.format_list_bulleted,
  'list-outline': Icons.format_list_bulleted,
  'star': Icons.star,
  'star-outline': Icons.star_outline,
  'heart': Icons.favorite,
  'heart-outline': Icons.favorite_outline,
  'bookmark': Icons.bookmark,
  'bookmark-outline': Icons.bookmark_outline,
  'pin': Icons.location_on,
  'location': Icons.location_on,
  'location-outline': Icons.location_on_outlined,
  'cloud-offline-outline': Icons.cloud_off_outlined,
  'wifi-off': Icons.wifi_off,
  'bug': Icons.bug_report,
  'bug-outline': Icons.bug_report_outlined,
  'copy': Icons.content_copy,
  'copy-outline': Icons.content_copy,
  'open-outline': Icons.open_in_new,
  'external-link': Icons.open_in_new,
  'play': Icons.play_arrow,
  'play-circle': Icons.play_circle,
  'play-circle-outline': Icons.play_circle_outlined,
  'percentage': Icons.percent,
  'stats-chart': Icons.insert_chart_outlined,
  'thermometer': Icons.thermostat,
  'sparkles': Icons.auto_awesome,
  'sparkles-outline': Icons.auto_awesome_outlined,
  'help': Icons.help,
  'help-circle': Icons.help,
  'help-circle-outline': Icons.help_outline,
  'information-circle': Icons.info,
  'information-circle-outline': Icons.info_outlined,
  'calendar-number': Icons.calendar_today,
  'calculator': Icons.calculate_outlined,
  'download': Icons.download,
  'share': Icons.share,
  'share-outline': Icons.share_outlined,
  'print': Icons.print,
  'save': Icons.save_outlined,
  'save-outline': Icons.save_outlined,
  'color-fill': Icons.format_color_fill,
  'paint': Icons.palette,
  'paint-outline': Icons.palette_outlined,
  'book': Icons.book_outlined,
  'send': Icons.send,
  'send-outline': Icons.send_outlined,
  'phone-landscape': Icons.screen_rotation,
  'timer': Icons.timer_outlined,
  'flower': Icons.local_florist,
  'water': Icons.water_drop,
  'snow': Icons.ac_unit,
  'flash': Icons.flash_on,
  'sunny': Icons.wb_sunny_outlined,
  'cloudy-night': Icons.dark_mode_outlined,
};

/// Nombre -> IconData. Decoración de Ionicons accent (p. ej. "add-circle"
/// frente a "add-circle-outline").
class Iconos {
  static IconData para(Object? nombre, {IconData fallback = Icons.help_outline}) {
    final n = nombre?.toString() ?? '';
    final icon = _iconos[n];
    if (icon != null) return icon;
    // Crash-insensitive: ignora sufijos de variante
    final base = n.replaceAll('-outline', '');
    final iconBase = _iconos[base];
    return iconBase ?? fallback;
  }
}

/// Icono de WhatsApp (no existe en Material; Font Awesome lo provee).
class IconoWhatsApp extends StatelessWidget {
  final double tamanho;
  final Color? color;

  const IconoWhatsApp({super.key, this.tamanho = 22, this.color});

  @override
  Widget build(BuildContext context) {
    return FaIcon(
      FontAwesomeIcons.whatsapp,
      size: tamanho,
      color: color ?? const Color(0xFF25D366),
    );
  }
}