-- ============================================================
-- LicorStock - Creacion de la base de datos (esquema)
-- Motor PostgreSQL 17 | Charset UTF8 (estandar)
-- Prefijo de tablas: LS_ (iniciales de LicorStock)
-- Uso: psql -U postgres -f licorstock.sql
-- ============================================================

-- Crea la base si no existe y se conecta a ella (meta-comando psql)
SELECT 'CREATE DATABASE licorstock'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'licorstock')\gexec
\connect licorstock

-- ------------------------------------------------------------
-- LS_USUARIOS (usuarios.Usuario - hereda AbstractUser)
-- rol: ADMIN | VENDEDOR
-- ------------------------------------------------------------
CREATE TABLE LS_USUARIOS (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password      VARCHAR(128) NOT NULL,
  last_login    TIMESTAMP NULL,
  is_superuser  BOOLEAN NOT NULL DEFAULT FALSE,
  username      VARCHAR(150) NOT NULL UNIQUE,
  first_name    VARCHAR(150) NOT NULL DEFAULT '',
  last_name     VARCHAR(150) NOT NULL DEFAULT '',
  email         VARCHAR(254) NOT NULL UNIQUE,
  is_staff      BOOLEAN NOT NULL DEFAULT FALSE,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  date_joined   TIMESTAMP NOT NULL,
  rol           VARCHAR(20) NOT NULL DEFAULT 'VENDEDOR',
  estado        BOOLEAN NOT NULL DEFAULT TRUE
);

-- ------------------------------------------------------------
-- LS_CATEGORIAS (inventario.Categoria)
-- ------------------------------------------------------------
CREATE TABLE LS_CATEGORIAS (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(100) NOT NULL,
  descripcion TEXT NULL,
  color       VARCHAR(9) NOT NULL DEFAULT '#C9A227',
  estado      BOOLEAN NOT NULL DEFAULT TRUE
);

-- ------------------------------------------------------------
-- LS_PRODUCTOS (inventario.Producto)
-- ------------------------------------------------------------
CREATE TABLE LS_PRODUCTOS (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id  INT NOT NULL,
  nombre        VARCHAR(200) NOT NULL,
  descripcion   TEXT NULL,
  precio_compra DECIMAL(10,2) NOT NULL,
  precio_venta  DECIMAL(10,2) NOT NULL,
  stock_minimo  INT NOT NULL DEFAULT 5,
  unidad        VARCHAR(20) NOT NULL DEFAULT 'UNIDAD',
  imagen        VARCHAR(100) NULL,
  estado        BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id)
    REFERENCES LS_CATEGORIAS(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- LS_INVENTARIO (inventario.Inventario) - existencias 1:1
-- ------------------------------------------------------------
CREATE TABLE LS_INVENTARIO (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id          INT NOT NULL UNIQUE,
  stock_actual         INT NOT NULL DEFAULT 0,
  fecha_actualizacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inv_producto FOREIGN KEY (producto_id)
    REFERENCES LS_PRODUCTOS(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- LS_MOVIMIENTOS_INVENTARIO (inventario.MovimientoInventario)
-- tipo: ENTRADA | SALIDA | AJUSTE
-- ------------------------------------------------------------
CREATE TABLE LS_MOVIMIENTOS_INVENTARIO (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id     INT NOT NULL,
  usuario_id      INT NULL,
  tipo_movimiento VARCHAR(20) NOT NULL,
  cantidad        INT NOT NULL,
  motivo          VARCHAR(255) NULL,
  fecha           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_mov_producto FOREIGN KEY (producto_id)
    REFERENCES LS_PRODUCTOS(id) ON DELETE CASCADE,
  CONSTRAINT fk_mov_usuario FOREIGN KEY (usuario_id)
    REFERENCES LS_USUARIOS(id) ON DELETE SET NULL
);

-- ------------------------------------------------------------
-- LS_CLIENTES (clientes.Cliente)
-- ------------------------------------------------------------
CREATE TABLE LS_CLIENTES (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         VARCHAR(200) NOT NULL,
  tipo_documento VARCHAR(20) NOT NULL DEFAULT 'CEDULA',
  documento      VARCHAR(20) NULL UNIQUE,
  telefono       VARCHAR(20) NULL,
  email          VARCHAR(254) NULL,
  direccion      VARCHAR(255) NULL,
  estado         BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- LS_VENTAS (ventas.Venta) - estado: COMPLETADA | ANULADA
-- ------------------------------------------------------------
CREATE TABLE LS_VENTAS (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero     VARCHAR(20) NOT NULL UNIQUE,
  cliente_id INT NULL,
  usuario_id INT NULL,
  subtotal   DECIMAL(12,2) NOT NULL DEFAULT 0,
  total      DECIMAL(12,2) NOT NULL DEFAULT 0,
  estado     VARCHAR(20) NOT NULL DEFAULT 'COMPLETADA',
  fecha      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_venta_cliente FOREIGN KEY (cliente_id)
    REFERENCES LS_CLIENTES(id) ON DELETE SET NULL,
  CONSTRAINT fk_venta_usuario FOREIGN KEY (usuario_id)
    REFERENCES LS_USUARIOS(id) ON DELETE SET NULL
);

-- ------------------------------------------------------------
-- LS_DETALLES_VENTA (ventas.DetalleVenta)
-- ------------------------------------------------------------
CREATE TABLE LS_DETALLES_VENTA (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id         INT NOT NULL,
  producto_id      INT NULL,
  nombre_producto  VARCHAR(200) NOT NULL,
  cantidad         INT NOT NULL,
  precio_unitario  DECIMAL(10,2) NOT NULL,
  subtotal         DECIMAL(12,2) NOT NULL,
  CONSTRAINT fk_det_venta FOREIGN KEY (venta_id)
    REFERENCES LS_VENTAS(id) ON DELETE CASCADE,
  CONSTRAINT fk_det_producto FOREIGN KEY (producto_id)
    REFERENCES LS_PRODUCTOS(id) ON DELETE SET NULL
);

-- ------------------------------------------------------------
-- LS_PAGOS_VENTA (ventas.PagoVenta)
-- metodo: EFECTIVO | TARJETA | TRANSFERENCIA | CREDITO
-- ------------------------------------------------------------
CREATE TABLE LS_PAGOS_VENTA (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id INT NOT NULL,
  metodo   VARCHAR(20) NOT NULL,
  monto    DECIMAL(12,2) NOT NULL,
  fecha    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pago_venta FOREIGN KEY (venta_id)
    REFERENCES LS_VENTAS(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- LS_DEUDAS (cuentas_por_cobrar.Deuda)
-- estado: PENDIENTE | PAGADA | ANULADA
-- ------------------------------------------------------------
CREATE TABLE LS_DEUDAS (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id        INT NOT NULL,
  venta_id          INT NOT NULL UNIQUE,
  monto_original    DECIMAL(12,2) NOT NULL,
  saldo_pendiente   DECIMAL(12,2) NOT NULL,
  estado            VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  fecha_inicio      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_vencimiento TIMESTAMP NULL,
  CONSTRAINT fk_deuda_cliente FOREIGN KEY (cliente_id)
    REFERENCES LS_CLIENTES(id) ON DELETE CASCADE,
  CONSTRAINT fk_deuda_venta FOREIGN KEY (venta_id)
    REFERENCES LS_VENTAS(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- LS_ABONOS (cuentas_por_cobrar.Abono)
-- ------------------------------------------------------------
CREATE TABLE LS_ABONOS (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deuda_id   INT NOT NULL,
  metodo     VARCHAR(20) NOT NULL DEFAULT 'EFECTIVO',
  monto      DECIMAL(12,2) NOT NULL,
  usuario_id INT NULL,
  fecha      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_abono_deuda FOREIGN KEY (deuda_id)
    REFERENCES LS_DEUDAS(id) ON DELETE CASCADE,
  CONSTRAINT fk_abono_usuario FOREIGN KEY (usuario_id)
    REFERENCES LS_USUARIOS(id) ON DELETE SET NULL
);

-- ------------------------------------------------------------
-- Indices para las consultas frecuentes
-- ------------------------------------------------------------
CREATE INDEX idx_producto_nombre      ON LS_PRODUCTOS(nombre);
CREATE INDEX idx_producto_estado      ON LS_PRODUCTOS(estado);
CREATE INDEX idx_mov_producto_fecha   ON LS_MOVIMIENTOS_INVENTARIO(producto_id, fecha);
CREATE INDEX idx_mov_tipo             ON LS_MOVIMIENTOS_INVENTARIO(tipo_movimiento);
CREATE INDEX idx_cliente_nombre       ON LS_CLIENTES(nombre);
CREATE INDEX idx_cliente_telefono     ON LS_CLIENTES(telefono);
CREATE INDEX idx_venta_fecha          ON LS_VENTAS(fecha);
CREATE INDEX idx_venta_estado         ON LS_VENTAS(estado);
CREATE INDEX idx_venta_cliente        ON LS_VENTAS(cliente_id);
CREATE INDEX idx_deuda_estado         ON LS_DEUDAS(estado);
CREATE INDEX idx_deuda_cliente        ON LS_DEUDAS(cliente_id);
CREATE INDEX idx_abono_deuda          ON LS_ABONOS(deuda_id);

-- ------------------------------------------------------------
-- Datos semilla minimos (categorias de ejemplo)
-- ------------------------------------------------------------
INSERT INTO LS_CATEGORIAS (nombre, descripcion, color) VALUES
  ('Cervezas',   'Cervezas nacionales e importadas', '#C9A227'),
  ('Licores',    'Whisky, ron, vodka, tequila',       '#8E44AD'),
  ('Vinos',      'Vinos tinto, blanco y espumante',   '#C0392B');